
# # -------------------------------- TREMSEN toolbox  ----------------------------------
# 
# # Version: 2.0
# 
# # Date: March 6, 2019
# 
# # Latest version available @ https://github.com/NIATS-UFU/TREMSEN-Toolbox.git
# 
# 
# 
# # Author: Prof. Adriano de Oliveira Andrade
# 
# # Contact email: adriano@ufu.br
# 
# # CV LATTES: http://lattes.cnpq.br/1229329519982110
# 
# # ORCID ID: http://orcid.org/0000-0002-5689-6606
# 
# # Researcher ID: http://www.researcherid.com/rid/D-9721-2012 
# 
# # GOOGLE ACADEMIC: https://scholar.google.com.br/citations?user=8nHKQHMAAAAJ&hl=pt-BR
# 
# 
# 
# 
# 
# # Adddress: Centre for Innovation and Technology Assessment in Health, 
# 
# #           Postgraduate Program in Electrical and Biomedical Engineering, 
# 
# #           Faculty of Electrical Engineering, Federal University of Uberl?ndia, 
# 
# #           Uberl?ndia, Brazil
# 
# # Webpage:  http://www.niats.feelt.ufu.br/
# 
# 
# 
# # Description: toolbox for processing data collected with the device TREMSEN
# 
# # ------------------------------------------------------------------------------------
# 

combinePulseAB <- function(PulseA, PulseB) {
  
  th <- 2
  
  
  
  ppA <- vector(length = length(PulseA))
  
  ppB <- vector(length = length(PulseB))
  
  
  
  ppA[which(PulseA < th)] <- 0
  
  ppA[which(PulseA > th)] <- 1
  
  
  
  ppB[which(PulseB > th)] <- 0
  
  ppB[which(PulseB < th)] <- 1
  
  
  
  pp <- as.numeric(ppA | ppB)
  
  
  
  return(pp)
  
}
#' @title  Combination of pulses A and B generated by TREMSEN.
#'   
#' @name combinePulseAB
#' 
#' @param PulseA : pulse A recorded in the data file of TREMSEN
#' 
#' @param PulseB : pulse B recorded in the data file of TREMSEN
#' 
#' @details The combination is based on the application of the function OR to the input pulses A and B
#' 
#' @return  Binary pulse resulting from the combination of pulses A and B
#' 
#' @author Prof. Adriano de Oliveira Andrade
#' 
#'