

LoadTREMSENFile <- function(Filename) {
  
  # Carregamento de arquivo do TREMSEN
  
  df = read.table(
    
    Filename,
    
    skip = 1,
    
    header = TRUE,
    
    sep = "\t",
    
    row.names = NULL,
    
    allowEscapes = TRUE
    
  )
  
  
  
  # foi necess?rio remover uma coluna pois o R n?o interpretou um caracter do arquivo original
  
  colnames(df) <- colnames(df)[2:ncol(df)] 
  
  df <- df[1:ncol(df) - 1]
  
  df[[1]] = as.numeric(df[[1]])
  
  
  
  
  
  # incluindo coluna que combina a resposta bin?ria dos pulsos A e B
  
  X.PULSE <- combinePulseAB(df$X.PULSE.A., df$X.PULSE.B.)
  
  X.PULSE <- movavg(X.PULSE, n=10, type='m')
  
  
  
  indx1 <- which(X.PULSE >= 0.5)
  
  indx2 <- which(X.PULSE < 0.5)
  
  X.PULSE[indx1] <- 1
  
  X.PULSE[indx2] <- 0
  
  
  
  
  
  wnd <- as.numeric(vector(length = length(X.PULSE)))
  
  
  
  j <- 1
  
  FLAG <- FALSE
  
  
  
  for (i in 1:length(X.PULSE)) {
    
    if (X.PULSE[i] == 1) {
      
      FLAG <- TRUE
      
      wnd[i] <- as.numeric(c(paste(j, sep = "")))
      
    }
    
    else
      
    {
      
      if (FLAG == TRUE) {
        
        j <- j + 1
        
      }
      
      
      
      FLAG = FALSE
      
    }
    
  }
  
  
  
  X.PULSE.LABEL <- factor(wnd)
  
  
  
  df <- cbind(df, as.data.frame(X.PULSE))
  
  df <- cbind(df, as.data.frame(X.PULSE.LABEL))
  
  
  
  return(df)
  
}
## LoadTREMSENFile-------------

#' @title  Load the data from the file `Filename` collected with TREMSEN
#'  
#' @name LoadTREMSENFile
#' 
#' @param Filename : file name, including path. This file should be a text file 
#'                  generated by the data acquisition software of TREMSEN

#' @return A dataframe with the loaded data
#' 
#' @author Prof. Adriano de Oliveira Andrade
#' 
#' @importFrom utils read.table
#' @importFrom pracma movavg
#' 
#' @examples  
#'           testFilename <- file.choose()
#'           df <- LoadTREMSENFile(testFilename)
#' 
#' 
#' 
#' 

